name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history required for conventional commit scanning

      - uses: actions/checkout@v4
        with:
          repository: blehwtf/.github
          ref: main
          path: .action-repo
          token: ${{ secrets.ORG_PAT }}

      - uses: ./.action-repo/.github/actions/semantic-version
        with:
          tag-prefix: v
          version-file: none
          create-release: true
