name: test-nanoc

on:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true   # runs bundle install and caches gems

      - name: RuboCop
        run: bundle exec rubocop

      - name: nanoc compile
        run: bundle exec nanoc compile

      - name: nanoc check
        run: bundle exec nanoc check html

      - name: nanoc check css
        run: bundle exec nanoc check css

      - name: nanoc check internal_links
        run: bundle exec nanoc check internal_links

      - name: nanoc check external_links
        run: bundle exec nanoc check external_links
